// Jenkinsfile for MLBParks
// Create a slave 
  podTemplate(
  label: "mlbparks-build",
  inheritFrom: "maven",
  cloud: "openshift",
  containers: [
    containerTemplate(
      name: "jnlp",
      image: "docker-registry.default.svc:5000/cpd-jenkins/maven-slave-pod",
      resourceRequestMemory: "1Gi",
      resourceLimitMemory: "2Gi"
    )
  ]
) {
  node('mlbparks-build') {

    // Define location of the Nexus setting file 
    def mvnCmd = "mvn -s ./nexus_settings.xml"

    // Set the tag for the development image: version + build number
    def devTag = "${version}-${BUILD_NUMBER}"

    // Set the tag for the production image: version
    def prodTag = "${version}"

    // Extract version and other properties from the pom.xml
    def groupId    = getGroupIdFromPom("./advdev_homework/MLBParks/pom.xml")
    def artifactId = getArtifactIdFromPom("./advdev_homework/MLBParks/pom.xml")
    def version    = getVersionFromPom("./advdev_homework/MLBParks/pom.xml")

    // Checkout Source Code
    stage('Checkout Source') {
      git url: 'https://github.com/carl-durrant/advdev_homework.git'
    }    
    // Using Maven build the war file
    stage('Build war') {
      echo "Building version ${devTag}"
      sh "${mvnCmd} -f ./advdev_homework/MLBParks/pom.xml clean package -DskipTests"
    }
  }
  }

// Convenience Functions to read variables from the pom.xml
// Do not change anything below this line.
// --------------------------------------------------------
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}
def getGroupIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<groupId>(.+)</groupId>'
  matcher ? matcher[0][1] : null
}
def getArtifactIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<artifactId>(.+)</artifactId>'
  matcher ? matcher[0][1] : null
}