kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "mlbparks-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/carl-durrant/advdev_homework"
      ref: "master"
  strategy:
    jenkinsPipelineStrategy:
       jenkinsfilePath: MLBParks/Jenkinsfile
  
